FSR-990 Request-Chat and Chat functionality
DEFRA/flood-webchat pull request #12
Opened 2023-11-01 08:53 UTC by ashleyjtaylor

**Screens**
- Request chat
- Chat
- Webchat unavailable

**Functionality**
- Request chat inputs with GDS error summary
- SDK setup and start chat functionality
- Display incoming and outgoing messages from agent and user
- Display _typing_ message when an agent is typing
- Update status bar when:
    - chat is connecting
    - when no adviser is available
    - when an agent is connected
    - when an agent has ended the chat
    - when the chat has ended and no agent is available

**Code**
`AppProvider`
- Handles the setting up of the state-managed functions and initialises the reducer
- Initialises the SDK and its chat events
- Exports 2 function:
    - `useApp` -> contains all the state properties and the functions to update them
    - `useChatSdk` -> contains functions to interact with the SDK

`appReducer`
- Handles the updating of state, depending on which dispatch came in

2023-11-14 09:27 UTC, nikiwycherley approved these changes

2023-11-14 09:54 UTC, maxcbc requested changes
Nice. This was an absolute beast of a task. 

I've a few changes mostly around test mocking and console logging.. We can jump on a call and discuss if it helps.

2023-11-16 10:04 UTC, maxcbc reviewed
I think the AppProvider needs more tests, but other than that looks good 👍

2023-11-20 09:35 UTC, maxcbc approved these changes
👍

2023-11-20 15:36 UTC, maxcbc approved these changes

2023-11-20 15:48 UTC, merged